//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcherLibraryTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string NumberBooking { get; set; }
        public string NumberPassengerPassport { get; set; }
        public string NumberFlightTicket { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
