//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public string Number_Flight { get; set; }
        public int Id_Name_Airline { get; set; }
        public System.DateTime Departure_Date { get; set; }
        public int Count_Place_All { get; set; }
        public int Count_Place_Remains { get; set; }
        public int Airport_From { get; set; }
        public int Airport_To { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport_Name Airport_Name { get; set; }
        public virtual Airport_Name Airport_Name1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
