//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public string NumberFlight { get; set; }
        public int IdNameAirline { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int CountPlaceAll { get; set; }
        public int CountPlaceRemains { get; set; }
        public int AirportFrom { get; set; }
        public int AirportTo { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual AirportFrom AirportFrom1 { get; set; }
        public virtual AirportTo AirportTo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
