//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportDispatcherEntities : DbContext
    {
        public AirportDispatcherEntities()
            : base("name=AirportDispatcherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airline> Airline { get; set; }
        public virtual DbSet<AirportFrom> AirportFrom { get; set; }
        public virtual DbSet<AirportTo> AirportTo { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
